services:
  backend:
    build: .
    ports:
      - "3007:3001"
    command: sh -c "npx prisma migrate reset --force && npx prisma generate && npx prisma migrate dev && npm run dev_docker_aws"
    volumes:
      - "./src:/app/src" #! Not readonly.   Avoid it if you plan on using prisma which generates the client in the src folder. 
    depends_on:
      - db
    env_file:
      - ./prisma/docker.env #$ Correctly set db connection on docker container for db


  db:
    image: postgres
    ports:
      - "5434:5432" #% Added + 2 because there is other postgres DBs on AWS
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oauth
    volumes:
      - paiky_data:/var/lib/postgresql/data







volumes:
  paiky_data:

